---
- include: os/Ubuntu.yml
  when: ansible_os_family == "Ubuntu"
  tags:
    - Shipwright

- include: os/EL.yml
  when: ansible_os_family == "EL"
  tags:
    - Shipwright

- include: os/Amazon.yml
  when: ansible_os_family == "Amazon"
  tags:
    - Shipwright
